import Navbar from "@/components/Navbar/Navbar";
import { env } from "@/next.config";
import { StoreContext } from "@/utils/Store";
import axios from "axios";
import { useContext, useEffect } from "react";

const Marketplace = () => {
    const { state, dispatch } = useContext(StoreContext);
    
    useEffect(() => {
        console.log(state.user);
    }, [state.user]);

    const mintNFTToWallet = async () => {
        const token = env.HASHCASE_API_KEY;
        console.log(token);
        
        let wallet_address;
        
        if(state?.user?.magic_wallet){
            wallet_address = state.user.magic_wallet;
        }else if(state?.user?.wallet_address){
            wallet_address = state.user.wallet_address;
        }else{
            return;
        }
        console.log("Sending request");

        const bodyParameters = {
            wallet_address: `${wallet_address}`,
            collection_id: 2,
            token_id: 1
        };
    
        const config = {
            headers: {
              "Content-Type": "application/json",
            },
        };
    
        axios.defaults.headers.common = {
            "x-api-key": token,
        };
        const res = await axios.post("https://api.hashcase.co/dev/mintNFTtoAccount", bodyParameters, config);
        console.log(res.data);

    }

    return (
        <>
            <Navbar />
            <div className="max-w-screen max-h-screen flex overflow-hidden">
                <div className="w-[50%] md:flex p-16">
                    <img
                        src="/images/sample_nft.png"
                        alt="Sample NFT"
                        style={{width:"100%"}}
                    />
                </div>
                <div className="md:w-[50%] max-w-screen flex justify-center items-center p-16">
                    <div className="flex flex-col items-start">
                        <h1 className="font-bebas text-4xl uppercase">
                            ROBERT TEAM
                        </h1>
                        <p className="text-[#667085]">
                            Graphic Leaf is a fine art collection of hand-drawn felines. is entirely unique and algorithmically generated by combining 33 unrepeatable traits with varying rarity across categories. As the first collection of the Greenvest  ecosystem, Graphic Leafwill provide anticipated access to future NFT collection.
                        </p>
                        <button
                            onClick={mintNFTToWallet}
                            className="text-white  bg-[#04A6E7] rounded-[1.5rem] px-4 py-2 hover:scale-105 hover:duration-150 hover:ease-in hover:delay-150 font-poppins mt-8"
                            style={{fontSize:"1.25rem"}}
                        >
                            Claim to wallet
                        </button>
                    </div>
                </div>
                
            </div>
        </>
    );
};

export default Marketplace;
